[package]
name = "hypertictactoe"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
rayon = "1.11.0"
rustc-hash = "2"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rand = "0.8"
